--------------------------------------------------------
--  파일이 생성됨 - 화요일-11월-26-2024   
--------------------------------------------------------
REM INSERTING into REVIEW
SET DEFINE OFF;
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (141,'디즈니 팝업 너무 기대돼요!!💖🎆',to_date('24/09/26','RR/MM/DD'),0,null,382,null,5,'이찬영 ');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (82,'ddddddddddddddddd',to_date('24/09/25','RR/MM/DD'),0,null,242,null,4,'csj');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (161,'재미있어요!',to_date('24/09/26','RR/MM/DD'),0,null,361,null,5,'이사람');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (81,'좋아요',to_date('24/09/25','RR/MM/DD'),0,null,221,null,4,'최기획');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (101,'gooooood',to_date('24/09/26','RR/MM/DD'),0,null,321,null,4,'최기획');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (142,'스탠리 정말 좋아요 !! 내구성도 좋고 추천합니당 다양한 스탠리 제품들을 볼 수 있어서 정말 좋았어요 !!',to_date('24/09/26','RR/MM/DD'),0,null,265,null,5,'이찬영 ');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (261,'행사에 대한 리뷰를 작성하는 공간입니다',to_date('24/11/22','RR/MM/DD'),0,null,421,null,3,'정성찬');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (181,'flq',to_date('24/09/27','RR/MM/DD'),0,null,401,null,4,'정성찬');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (2,'리뷰 2',to_date('24/09/23','RR/MM/DD'),0,null,1,null,3,'테스트1');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (21,'평점테스트',to_date('24/09/23','RR/MM/DD'),0,null,1,null,2,'테스트1');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (143,'마치 제가 진짜 동숲 세계에 있는 것 같은 느낌쓰 ~ 추천 !!',to_date('24/09/26','RR/MM/DD'),0,null,261,null,4,'이찬영 ');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (182,'리뷰><',to_date('24/09/27','RR/MM/DD'),0,null,401,null,1,'정성찬');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (241,'행사가 기대되네요!',to_date('24/11/12','RR/MM/DD'),0,null,421,null,4,'김현수');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (242,'정말 재밌었어요!!!',to_date('24/11/12','RR/MM/DD'),0,null,382,null,4,'김현수');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (41,'리뷰 평점테스트 22',to_date('24/09/23','RR/MM/DD'),0,null,1,null,3,'테스트1');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (121,'정말 너무 재미있었어용',to_date('24/09/26','RR/MM/DD'),0,null,321,null,1,'내가누구게');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (183,'리뷰!!',to_date('24/09/27','RR/MM/DD'),0,null,401,null,3,'정성찬');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (201,'호랑이 귀여워요!',to_date('24/09/27','RR/MM/DD'),0,null,283,null,5,'이사람');
Insert into REVIEW (REVIEW_NO,CONTENT,CREATED_DATE,IS_DELETED,DELETED_DATE,EVENT_NO,MODIFIED_DATE,RATING,USER_ID) values (202,'알차고 재미있었어요!',to_date('24/09/27','RR/MM/DD'),0,null,283,null,4,'장동건');
